export const pricingPlans = [
  // VPS Plans
  {
    name: "KVM 1",
    originalPrice: "Rs. 3,390",
    discount: "56% OFF",
    price: "Rs. 1,490/mo",
    renewalPrice: "Rs. 2,390/mo",
    specs: [
      "1 vCPU core",
      "4 GB RAM",
      "50 GB NVMe disk space",
      "4 TB bandwidth",
      "Data centers worldwide",
      "Linux operating systems",
    ],
    type: "vps",
  },
  {
    name: "KVM 2",
    originalPrice: "Rs. 5,390",
    discount: "65% OFF",
    price: "Rs. 1,890/mo",
    renewalPrice: "Rs. 3,190/mo",
    specs: [
      "2 vCPU cores",
      "8 GB RAM",
      "100 GB NVMe disk space",
      "8 TB bandwidth",
      "Data centers worldwide",
      "Linux operating systems",
    ],
    type: "vps",
  },
  {
    name: "KVM 4",
    originalPrice: "Rs. 8,790",
    discount: "67% OFF",
    price: "Rs. 2,890/mo",
    renewalPrice: "Rs. 6,790/mo",
    specs: [
      "4 vCPU cores",
      "16 GB RAM",
      "200 GB NVMe disk space",
      "16 TB bandwidth",
      "Data centers worldwide",
      "Linux operating systems",
    ],
    type: "vps",
  },

  // Web Plans
  {
    name: "Single",
    originalPrice: "Rs. 1,390",
    discount: "79% OFF",
    price: "Rs. 290/mo",
    renewalPrice: "Rs. 690/mo",
    specs: [
      "1 website",
      "Managed Hosting for WordPress",
      "~10,000 visits monthly",
      "10 GB SSD storage",
      "200,000 files and directories (inodes)",
      "Free pre-built templates",
      "Free automatic website migration",
      "Unlimited free SSL",
      "1 mailbox",
      "Weekly backups",
      "WordPress vulnerabilities scanner",
      "Smart WordPress auto updates",
      "Standard WordPress acceleration",
      "100 GB bandwidth",
      "Free domain (Rs. 2,499 value)",
      "Free CDN",
      "WordPress AI tools",
      "WordPress staging tool",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "web",
  },
  {
    name: "Premium",
    originalPrice: "Rs. 1,999",
    discount: "75% OFF",
    price: "Rs. 499/mo",
    renewalPrice: "Rs. 1,099/mo",
    specs: [
      "25 websites",
      "Managed Hosting for WordPress",
      "~25,000 visits monthly",
      "25 GB SSD storage",
      "400,000 files and directories (inodes)",
      "Free pre-built templates",
      "Free automatic website migration",
      "Unlimited free SSL",
      "25 mailboxes",
      "Weekly backups",
      "WordPress vulnerabilities scanner",
      "Smart WordPress auto updates",
      "Standard WordPress acceleration",
      "Unlimited bandwidth",
      "Free domain (Rs. 2,499 value)",
      "Free CDN",
      "WordPress AI tools",
      "WordPress staging tool",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "web",
  },
  {
    name: "Business",
    originalPrice: "Rs. 2,499",
    discount: "70% OFF",
    price: "Rs. 749/mo",
    renewalPrice: "Rs. 1,899/mo",
    specs: [
      "50 websites",
      "Managed Hosting for WordPress",
      "~100,000 visits monthly",
      "50 GB NVMe storage",
      "600,000 files and directories (inodes)",
      "Free pre-built templates",
      "Free automatic website migration",
      "Unlimited free SSL",
      "50 mailboxes",
      "Daily and on-demand backups",
      "WordPress vulnerabilities scanner",
      "Smart WordPress auto updates",
      "Advanced WordPress acceleration",
      "Unlimited bandwidth",
      "Free domain (Rs. 2,499 value)",
      "Free CDN",
      "WordPress AI tools",
      "WordPress staging tool",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "web",
  },

  // Cloud Plans
  {
    name: "Cloud Startup",
    originalPrice: "Rs. 5,690",
    discount: "58% OFF",
    price: "Rs. 2,390/mo",
    renewalPrice: "Rs. 4,290/mo",
    specs: [
      "~200,000 visits monthly",
      "Up to 100 websites",
      "Managed Hosting for WordPress",
      "100 GB NVMe storage",
      "2,000,000 files and directories (inodes)",
      "100 PHP workers",
      "3 GB RAM",
      "2 CPU cores",
      "Free domain (Rs. 2,499 value)",
      "Free SSL",
      "100 mailboxes",
      "Free CDN",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "cloud",
  },
  {
    name: "Cloud Professional",
    originalPrice: "Rs. 10,090",
    discount: "66% OFF",
    price: "Rs. 3,390/mo",
    renewalPrice: "Rs. 7,790/mo",
    specs: [
      "~300,000 visits monthly",
      "Up to 200 websites",
      "Managed Hosting for WordPress",
      "200 GB NVMe storage",
      "3,000,000 files and directories (inodes)",
      "200 PHP workers",
      "6 GB RAM",
      "4 CPU cores",
      "Free domain (Rs. 2,499 value)",
      "Free SSL",
      "100 mailboxes",
      "Free CDN",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "cloud",
  },
  {
    name: "Cloud Enterprise",
    originalPrice: "Rs. 18,190",
    discount: "54% OFF",
    price: "Rs. 8,390/mo",
    renewalPrice: "Rs. 16,090/mo",
    specs: [
      "~400,000 visits monthly",
      "Up to 300 websites",
      "Managed Hosting for WordPress",
      "300 GB NVMe storage",
      "4,000,000 files and directories (inodes)",
      "300 PHP workers",
      "12 GB RAM",
      "6 CPU cores",
      "Free domain (Rs. 2,499 value)",
      "Free SSL",
      "100 mailboxes",
      "Free CDN",
      "Dedicated IP address",
      "Priority support",
    ],
    type: "cloud",
  },
];
